import { Box, makeStyles } from '@material-ui/core';
import * as React from 'react'
import { ParaTypography, SubTitleTextTypography, TitleTextTypography } from './typography';
import { KeyTakeaways } from './KeyTakeaways';
import PeersReport from './PeersReport';

const useStyles = makeStyles((theme) => {
  return {
    root: {
      margin: 'auto',
      minHeight: '70vh',
      fontSize: '15px'
    },
    content: {
      maxWidth: '70%',
      margin: 'auto'
    }
  }
});


export const HOLDINGS = (props) => {
  const classes = useStyles();

  const keyTakeaways = [
    "Higher stake of promoters high confidence in the company. Increasing promoters holdings boost confidence that results into price appreciations or downside protection of the stock.",
    "Lower stake of promoters low confidence in the company. Try to avoid companies where promoters have small share holdings or they are consistently reducing their stake by a huger percentage",
    "Institutional investor(FII|DII) has more idea next to promoters.",
    "FII considers as the darlings of the company. They drivers of stock market.",
    "The key multi bagger investing lies in identifying a stock that can be become favourite among FIIs in the near future. ",
    "Increasing institutional holdings is a followed by sharp run up in stock price.",
    "Not much effect on stock price in terms of retail investor",
    "IF a company has a pledging shares up to 2%-8%, then it can be ignored",
    "More pledging shares is a risky thing"
  ]

  const data = props.peersData;

  return (
    <Box className={classes.root}>
      <Box className={classes.content}>
        <TitleTextTypography variant="h1"> Holdings </TitleTextTypography>
        {/* <Box m={4}>
          <SubTitleTextTypography variant="h2">What Is Return on Equity (ROE)?</SubTitleTextTypography>
          <ParaTypography variant="body1">How much profit generated by shareholders money. Return on equity (ROE) measures how effectively management is using a company’s assets to create profits.</ParaTypography>
        </Box>
        <Box m={4}>
          <SubTitleTextTypography variant="h2">What Does ROE Tell You?</SubTitleTextTypography>
          <ParaTypography variant="body1" >A good rule of thumb is to target an ROE that is equal to or just above the average for the peer group. For example, assume a company, TechCo, has maintained a steady ROE of 18% over the last few years compared to the average of its peers, which was 15%. As a shortcut, investors can consider an ROE near the long-term average of the S&P 500 (14%) as an acceptable ratio and anything less than 10% as poor.</ParaTypography>
        </Box> */}

        <KeyTakeaways title={"ROE"} keyTakeaways={keyTakeaways} />
      </Box>
      <PeersReport type='HOLDING' data={data} property="ROE" suffix="%" />
    </Box>
  )
}